version: '3.7'
services:
  db:
    container_name: pg-facet-db
    build:
      dockerfile: Dockerfile.postgres
    ports:
      - "127.0.0.1:5439:5432"
    environment:
      POSTGRES_PASSWORD: password
    labels:
      com.example.name: pg-facet-db
